#+TITLE: Summary of Algebraic Properties of Cellular Automata 
#+SUBTITLE: by Olivier Martin, Andrew M. Odlyzk and Stephen Wolfram
#+AUTHOR: Leonard Hardiman
#+INCLUDE: "../html/header.html" export html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../html/org-inverted.css"/>
#+OPTIONS: toc:nil num:3 H:4 ^:nil pri:t ':t
#+BEGIN_abstract
This text provides an analysis of the global properties of a class of finite cellular automata (CA) using algebraic techniques.
#+END_abstract
#+TOC: headlines 2

* Key points
- [X] Throughout this paper the set of states is taken to be a (finite) field $\mathbb{K}$. Configurations of an $n\hspace{-0.25em}$ -dimensional CA are represented as a polynomial in $n$ variables, so for example a 1D configuration $A^{(t)}$ with $N$ cells would be written as $$A^{(t)}(x) = \sum_{i=0}^{N-1} a_{i}^{(t)}\cdot x^{i}.$$ 

- [X] The authors focus on a class of cellular automata which exhibit an additivity feature. So called "additive cellular automata" allow for a natural representation of the configurations by certain characteristic polynomials. (Page 3).

  + *Definition of an additive CA* 
    #+BEGIN_fragile
    We start by only considering the 1D case, and then generalise. A 1D CA is called additive (over a field $\mathbb{K}$) if its set of states is $\mathbb{K}$ and each cell's upcoming state is given as a weighted sum of its current state together with its neighbours current states. This may be written in terms of the characteristic polynomials as follows,
    $$A^{(t)}(x) \cong \mathbb{T}(x) \cdot A^{(t-1)}(x) \mod(x^N-1).$$  
    
    We note that, for any additive CA together with two initial conditions $A^{(0)}, B^{(0)}$ and $t \in \mathbb{N}$, we have 
    $$(A^{(0)} + B^{(0)})^{(t)} = A^{(t)} + B^{(t)},$$ 
    where addition denotes cell by cell addition in $\mathbb{K}$.
    #+END_fragile

- [ ] "Global properties of cellular automata are then determined by algebraic properties of these polynomials"
  

- [ ] The paper also discusses non-additive cellular automata, for which the algebraic techniques are inapplicable. However, combinatorial methods are used to derive some results for a particular example (Page 5).

- [X] The paper applies its framework to derive a number of theorems on its main case study CA, for example:
  * *Theorem 3.1* (Page 8) 
    #+BEGIN_fragile
    The fraction of the $2^N$ possible configurations of the size N cellular automaton defined in Sect. 3A which can occur only as initial states, and cannot be reached by evolution, is 1/2 for N odd and 3/4 for N even.
    #+END_fragile

  * *Theorem 3.2* (Page 9) 
    #+BEGIN_fragile
    Configurations in the cellular automaton defined in Sect. 3A which have at least one predecessor have exactly two predecessors for N odd and exactly four for N even.
    #+END_fragile

* The case study

* Notes
+ Very strangely, the authors called Laurent polynomials "dipolynomials", and seem unaware that the ring of Laurent polynomials over a field is a super famous example of a PID! Hard to believe that got past peer review, I may be misunderstanding something?
